name: Verify

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: "Verify"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: "npm"
      - run: npm install
      - run: npx hardhat compile
      - run: npm run format:check
      - run: npm run lint
      - run: npm run type-check
      - run: npm test

  scan:
    needs: lint
    if: github.event_name == 'pull_request'
    uses: circlefin/circle-public-github-workflows/.github/workflows/pr-scan.yaml@v1

  release-sbom:
    needs: lint
    if: github.event_name == 'push'
    uses: circlefin/circle-public-github-workflows/.github/workflows/attach-release-assets.yaml@v1
